server:
  port: 8761

# Because it is our server, we don't need to fetch registry and connect to the client.
eureka:
  instance:
    hostname: "${HOSTNAME}.eureka"
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}


#We will be passing it through environment variable from config map.
