apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
  labels:
    app: user-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
      - name: user-service-app
        image: prakash472/user-service:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
  namespace: default
spec:
  selector:
    app: user-service-app
  type: ClusterIP
  ports:
  - name: user-service-port
    port: 80
    targetPort: 8081
---